[package]
name = "guessing_game_server"
version = "0.1.0"
authors = ["Guillaume Charmetant <cguille.dev@gmail.com>"]

[dependencies]
rand = "*"
sluggen = { git = "https://github.com/cGuille/sluggen.git" }